name: Build image

on:
  workflow_call:
    inputs:
      docker-registry:
        default: asia.gcr.io
        type: string
      docker-image: 
        required: true
        type: string
      docker-tag: 
        required: true
        type: string
      setup-platforms:
        default: arm64
        type: string
      build-platforms: 
        type: string
        default: linux/arm64
      build-args: 
        type: string
        default: ""
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      project_id:
        required: true
        type: string

jobs:
  build-image:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Auth GCP 
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          project_id: ${{ inputs.project_id }}

      # This example uses the docker login action
      - name: Auth GCP 
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ inputs.docker-registry }}
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.id_token }}'
      - run: |-
          echo '${{ steps.auth.outputs.id_token }}' | docker login -u oauth2accesstoken --password-stdin https://${{ inputs.docker-registry }}    

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.build-platforms }}
          push: true
          tags: ${{ inputs.docker-image }}:${{ inputs.docker-tag }}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
