name: Build image

on:
  workflow_call:
    inputs:
      docker-image: 
        required: true
        type: string
      docker-tag: 
        required: true
        type: string
      setup-platforms:
        default: arm64
        type: string
      build-platforms: 
        type: string
        default: linux/arm64
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
    secrets:
      GCP_SERVICE_KEY:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Auth GCP 
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.build-platforms }}
          push: true
          tags: ${{ inputs.docker-image }}:${{ inputs.docker-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
