name: Semantic release

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true
    inputs:
      BUILD_NUMBER:
        type: string
        required: false
    outputs:
      tag: 
        description: "Tag"
        value: ${{ jobs.release-tag.outputs.tag }}
      new_release_published: 
        description: "New release published"
        value: ${{ jobs.release-tag.outputs.new_release_published }}
      latest_tag: 
        description: "Latest tag"
        value: ${{ jobs.release-tag.outputs.latest_tag }}

jobs:
  release-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      new_release_published: ${{ steps.tag.outputs.new_release_published }}
      latest_tag: ${{ steps.latest-tag.outputs.latest_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT || github.token  }}
        with:
          semantic_version: 19
          tag_format: v${version}+${{ inputs.BUILD_NUMBER }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}

      - name: Tag
        id: tag
        run: |
          echo "new_release_published=${{ steps.semantic.outputs.new_release_published }}" >> $GITHUB_OUTPUT
          TAG=${{ steps.semantic.outputs.new_release_version }}
          echo $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Latest tag
        id: latest-tag
        run: |
          LATEST_TAG_V=$(git describe --tags --abbrev=0)
          echo $LATEST_TAG_V
          LATEST_TAG=${LATEST_TAG_V:1}
          echo $LATEST_TAG
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
